name: need_give_core
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  mime: ^1.0.2
  get_it: ^7.2.0
  path_provider: ^2.0.11
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.need_give_core
    iosBundleIdentifier: com.example.needGiveCore
